# Database type you want to use. Default: sqlite
type: sqlite
# If your database type has been set to mysql fill out these details
mysql:
    host: "localhost"
    port: 3306
    database: "stay_put"
    username: "root"
    password: ""

# Blacklisted worlds, which worlds should be excluded from the teleport actions? Default: []
# Example layout
# blacklisted-worlds:
#     - world
#     - world_nether
blacklisted-worlds: []

# Want to debug and see why certain actions are (not) executed? Set this to true. Default: false
debug: false